### ISSUE TITLE
Trouble with installation instructions, throwing errors

### ISSUE THREAD

**Issue by shannonjensen** [DSchau/gatsby-mail#15]
I followed the instructions in the readme, but `npm run develop` is throwing errors and failing. Thank you for the help.

![image](https://user-images.githubusercontent.com/11382877/47577378-a7ba3c00-d93e-11e8-9f76-b91c3f5c7511.png)
![image](https://user-images.githubusercontent.com/11382877/47577386-b0ab0d80-d93e-11e8-94a5-ab6a9f964470.png)
![image](https://user-images.githubusercontent.com/11382877/47577402-b9034880-d93e-11e8-9089-59f32237d43e.png)

**Comment by DSchau** [comment]
Hi Shannon!

Thanks for asking, so the error is that the graphql plugin can't authenticate with Github's GraphQL API.

I think you should just need to follow this step, but let me know if that doesn't work out for you!

> Request a Github token and give repo full access to the token
> cat .env.sample > .env.development then paste in your access token from gitub

It should end up looking like

```
GITHUB_API_TOKEN=your-token-here
```

**Comment by DSchau** [comment]
@shannonjensen gonna be proactive here, fairly certain that's the issue so please re-open if that wasn't the case!
