### ISSUE TITLE
Thanks for building this 

### ISSUE THREAD

**Issue by i001962** [DSchau/gatsby-mail#20]
I had been looking for an Apollo example for gatsby when I came across this. Good stuff. Interesting OG service too. Checking it out for a project.

**Comment by DSchau** [comment]
Hey!

Thanks for saying this--people don't open up issues often enough to express thanks, so so glad and appreciative of you doing this ❤️

As far as OG, OneGraph is amazing. Helped me build this out super quickly using a technology that I love (GraphQL). If you haven't already, check out [their site](https://www.onegraph.com/).

cc @sgrove
